#!/bin/bash
mv 1900nMMutS_1_R1.fastq.gz                     1_MutS_1900nM_R1.fastq.gz         
mv 1900nMMutS_1_R2.fastq.gz                     1_MutS_1900nM_R2.fastq.gz
mv 1900nMMutS_2_R1.fastq.gz                     2_MutS_1900nM_R1.fastq.gz
mv 1900nMMutS_2_R2.fastq.gz                     2_MutS_1900nM_R2.fastq.gz
mv 950nMMutS_1_R1.fastq.gz                      1_MutS_950nM_R1.fastq.gz
mv 950nMMutS_1_R2.fastq.gz                      1_MutS_950nM_R2.fastq.gz
mv 950nMMutS_2_R1.fastq.gz                      2_MutS_950nM_R1.fastq.gz
mv 950nMMutS_2_R2.fastq.gz                      2_MutS_950nM_R2.fastq.gz
mv DopedTemp_R1.fastq.gz                        1_DopedTemp_R1.fastq.gz
mv DopedTemp_R2.fastq.gz                        1_DopedTemp_R2.fastq.gz
mv EndoV_1_R1.fastq.gz                          1_EndoV_R1.fastq.gz
mv EndoV_1_R2.fastq.gz                          1_EndoV_R2.fastq.gz
mv EndoV_2_R1.fastq.gz                          2_EndoV_R1.fastq.gz
mv EndoV_2_R2.fastq.gz                          2_EndoV_R2.fastq.gz
mv ErrASE_1_R1.fastq.gz                         1_ErrASE_R1.fastq.gz
mv ErrASE_1_R2.fastq.gz                         1_ErrASE_R2.fastq.gz
mv ErrASE_2_R1.fastq.gz                         2_ErrASE_R1.fastq.gz
mv ErrASE_2_R2.fastq.gz                         2_ErrASE_R2.fastq.gz
mv ErrASE-nonDoped_1_R1.fastq.gz                1_ErrASE-nonDoped_R1.fastq.gz
mv ErrASE-nonDoped_1_R2.fastq.gz                1_ErrASE-nonDoped_R2.fastq.gz
mv ErrASE-nonDoped_2_R1.fastq.gz                2_ErrASE-nonDoped_R1.fastq.gz
mv ErrASE-nonDoped_2_R2.fastq.gz                2_ErrASE-nonDoped_R2.fastq.gz
mv nonDoped_R1.fastq.gz                         1_nonDoped_R1.fastq.gz
mv nonDoped_R2.fastq.gz                         1_nonDoped_R2.fastq.gz
mv Surveyor_1_R1.fastq.gz                       1_Surveyor_R1.fastq.gz
mv Surveyor_1_R2.fastq.gz                       1_Surveyor_R2.fastq.gz
mv Surveyor_2_R1.fastq.gz                       2_Surveyor_R1.fastq.gz
mv Surveyor_2_R2.fastq.gz                       2_Surveyor_R2.fastq.gz
mv T4EndoVII_1_R1.fastq.gz                      1_T4EndoVII_R1.fastq.gz
mv T4EndoVII_1_R2.fastq.gz                      1_T4EndoVII_R2.fastq.gz
mv T4EndoVII_2_R1.fastq.gz                      2_T4EndoVII_R1.fastq.gz
mv T4EndoVII_2_R2.fastq.gz                      2_T4EndoVII_R2.fastq.gz
mv T7EndoI_1_R1.fastq.gz                        1_T7EndoI_R1.fastq.gz
mv T7EndoI_1_R2.fastq.gz                        1_T7EndoI_R2.fastq.gz
mv T7EndoI_2_R1.fastq.gz                        2_T7EndoI_R1.fastq.gz
mv T7EndoI_2_R2.fastq.gz                        2_T7EndoI_R2.fastq.gz
mv T7EndoI-e3T7Ligase_1_R1.fastq.gz             1_T7EndoI-e3T7Ligase_R1.fastq.gz
mv T7EndoI-e3T7Ligase_1_R2.fastq.gz             1_T7EndoI-e3T7Ligase_R2.fastq.gz
mv T7EndoI-e3T7Ligase_2_R1.fastq.gz             2_T7EndoI-e3T7Ligase_R1.fastq.gz
mv T7EndoI-e3T7Ligase_2_R2.fastq.gz             2_T7EndoI-e3T7Ligase_R2.fastq.gz
mv T7EndoI-e4T7Ligase_1_R1.fastq.gz             1_T7EndoI-e4T7Ligase_R1.fastq.gz
mv T7EndoI-e4T7Ligase_1_R2.fastq.gz             1_T7EndoI-e4T7Ligase_R2.fastq.gz
mv T7EndoI-e4T7Ligase_2_R1.fastq.gz             2_T7EndoI-e4T7Ligase_R1.fastq.gz
mv T7EndoI-e4T7Ligase_2_R2.fastq.gz             2_T7EndoI-e4T7Ligase_R2.fastq.gz
mv T7EndoIFurhmann_1_R1.fastq.gz                1_T7EndoIFurhmann_R1.fastq.gz
mv T7EndoIFurhmann_1_R2.fastq.gz                1_T7EndoIFurhmann_R2.fastq.gz
mv T7EndoIFurhmann_2_R1.fastq.gz                2_T7EndoIFurhmann_R1.fastq.gz
mv T7EndoIFurhmann_2_R2.fastq.gz                2_T7EndoIFurhmann_R2.fastq.gz
